# Generated by Django 4.0.5 on 2022-07-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_createtime_guestbook_create_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestbook',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Текста'},
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default=[('active', 'Активно'), ('blocked', 'Заблокировано')], max_length=15, verbose_name='Статус'),
        ),
    ]
