# Generated by Django 4.0.5 on 2022-07-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_guestbook_options_alter_guestbook_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=15, verbose_name='Статус'),
        ),
    ]
